name: roofinspector
description: "Roof Inspector Android App"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  syncfusion_flutter_sliders: ^25.2.6
  cupertino_icons: ^1.0.2
  svg_flutter: ^0.0.1
  flutter_joystick: ^0.0.4
  google_fonts: ^6.2.1
  http: ^1.2.1
  network_info_plus: ^5.0.3
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  flutter_ffmpeg: ^0.4.2
  open_settings_plus: ^0.3.3
  android_intent: ^2.0.2
  flutter_internet_signal: ^0.0.30


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/png/example ai logo.png
    - assets/images/jpg/damaged_roof.jpg



